name: KnyoLink CICD

on:
  push:
    branches: 
        -  master
     
jobs:

  build:

    runs-on: windows-latest

    env:
      PROJECT_PATH: KnyoLink/KnyoLink.csproj
      #Solution_Name: YourSolution.sln
      #Test_Project_Path: YourApp.Tests\YourApp.Tests.csproj
      #Wap_Project_Directory: YourWapProject
      #Wap_Project_Path: YourWapProject\YourWapProject.wapproj

      Solution_Name: KnyoLink.sln
      Test_Project_Path: knyo-link.KnyoLink\knyo-link.KnyoLink.csproj
      Wap_Project_Directory: C:\Users\Dell\Desktop\ForTestWith6.0Knyolink\knyo-link
      Wap_Project_Path: C:\Users\Dell\Desktop\ForTestWith6.0Knyolink\knyo-link

    steps:
   
    - name: Setup .NET Framework
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 4.8.x
